# Generated by Django 4.2.1 on 2026-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_card',
            field=models.CharField(default=1, max_length=18, unique=True, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(help_text='用户姓名', max_length=150, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='用户账号', max_length=150, null=True, unique=True, verbose_name='用户账号'),
        ),
    ]
